apiVersion: v2
name: biosdk-service
description: A Helm chart for TF-GOVSTACK Auditmanager module
type: application
version: 12.0.1-GB3
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://tf-govstack.github.io
keywords:
  - mosip
  - biosdk-service
  - kernel
maintainers:
  - email: info@mosip.io
    name: MOSIP
