apiVersion: v2
name: admin-hotlist
description: A Helm chart for TF-GOVSTACK Admin Hotlist
type: application
version: 12.0.1-GB2
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://tf-govstack.github.io
keywords:
  - mosip
  - admin
  - hotlist
maintainers:
  - email: info@mosip.io
    name: MOSIP
