apiVersion: v2
name: artifactory
description: A Helm chart for TF-GOVSTACK Artifactory
type: application
version: 12.0.1-GB3
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://tf-govstack.github.io
keywords:
  - artifactory
  - antivirus
  - anti-virus
maintainers:
  - email: info@mosip.io
    name: MOSIP
